SiteLocaly/Controllers/ConnexionController.cs
using SiteLocaly.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteLocaly.Controllers
{
    public class ConnexionController : Controller
    {
        LOCALYEntities Context = new LOCALYEntities();

        [HttpGet]
        public ActionResult Authentification()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Authentification(LoginModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            } else
            {
                //Test
                if(model.Username == "Test" && model.Password == "Test")
                {
                    Session["UserID"] = Guid.NewGuid();
                    return RedirectToAction("Acceuil", "Home");
                } else
                {
                    //Check base
                    var encPass = Tools.Security.Encrypt(model.Password);
                    var user = Context.Utilisateur.SingleOrDefault(u => (u.motDePasse == encPass) && (u.prenom.ToUpper() + "." + u.nom.ToUpper() == model.Username.ToUpper()));
                    if(user != null)
                    {
                        Session["UserID"] = Guid.NewGuid();
                        return RedirectToAction("Acceuil", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("Erreur", "Mot de passe ou nom d'utilisateur erroné.");
                        return View(model);
                    }
                }
            }
        }
    }
}

SiteLocaly/Views/Shared/Authentification.cshtml
@model SiteLocaly.Models.LoginModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Localy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="jumbotron">
        <h1>Connexion</h1>

        @using (Html.BeginForm("Authentification", "Connexion"))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationMessage("Erreur")
            <hr />
            <br />
            @Html.TextBoxFor(m => m.Username, new { placeholder = "Utilisateur" })
            <br />
            <br />

            @Html.TextBoxFor(m => m.Password, new { placeholder = "Mot de passe", type = "password" })
            <br />
            <br />
            <button type="submit" class="btn btn-success">Se connecter</button>
        }
    </div>
    <div class="container body-content">


        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Localy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


</body>
</html>

SiteLocaly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Localy</title><!-- Leaflet CSS-->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin="" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Localy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/Home/Acceuil">Accueil <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">En savoir  plus</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Prix</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">A propos</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Localy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    
</body>
</html>